Repository martincostello/dotnet-bumper, pull requests merged in 2024-03, with the labels that each got.

#98 Add FAQs
  README.md
  docs/faq.md
Labels: documentation, enhancement

#101 Update NuGet badge
  README.md
Labels: documentation

#107 Include NuGet Package Microsoft.EntityFrameworkCore
  src/DotNetBumper.Core/BumperConfigurationProvider.cs
  tests/DotNetBumper.Tests/BumperConfigurationProviderTests.cs
Labels: bug

#109 Handle more Runtime Identifier operating systems
  src/DotNetBumper.Core/RuntimeIdentifier.cs
  tests/DotNetBumper.Tests/RuntimeIdentifierHelpersTests.cs
  tests/DotNetBumper.Tests/RuntimeIdentifierTests.cs
Labels: bug, enhancement

#112 Refactor RID handling
  src/DotNetBumper.Core/DotNetBumper.Core.csproj
  src/DotNetBumper.Core/Resources/runtime-identifiers.json
  src/DotNetBumper.Core/Resources/runtime-identifiers.portable.json
  src/DotNetBumper.Core/RuntimeIdentifier.cs
  src/DotNetBumper.Core/RuntimeIdentifierHelpers.cs
  tests/DotNetBumper.Tests/PostProcessors/LeftoverReferencesPostProcessorTests.cs
  tests/DotNetBumper.Tests/RuntimeIdentifierHelpersTests.cs
  tests/DotNetBumper.Tests/RuntimeIdentifierTests.cs
Labels: bug, enhancement

#115 Simplify Regex
  src/DotNetBumper.Core/RuntimeIdentifier.cs
Labels: enhancement, .NET

#118 Use JSON source generator for RIDs
  src/DotNetBumper.Core/RuntimeIdentifier.cs
Labels: enhancement

#122 Fix over-aggressive Docker version updates
  src/DotNetBumper.Core/Upgraders/DockerfileUpgrader.cs
  tests/DotNetBumper.Tests/Upgraders/DockerfileUpgraderTests.cs
Labels: bug

#119 Update PowerShell scripts
  Directory.Build.props
  Directory.Packages.props
  src/DotNetBumper.Core/DotNetBumper.Core.csproj
  src/DotNetBumper.Core/PathHelpers.cs
  src/DotNetBumper.Core/PostProcessors/LeftoverReferencesPostProcessor.cs
  src/DotNetBumper.Core/PowerShellScript.cs
  src/DotNetBumper.Core/ServiceCollectionExtensions.cs
  src/DotNetBumper.Core/Upgraders/PowerShellScriptUpgrader.cs
  src/DotNetBumper.Core/Upgraders/ServerlessUpgrader.cs
  src/DotNetBumper.Core/YamlHelpers.cs
  tests/DotNetBumper.Tests/EndToEndTests.cs
  tests/DotNetBumper.Tests/Project.cs
  tests/DotNetBumper.Tests/Upgraders/PowerShellScriptUpgraderTests.cs
Labels: enhancement

#123 Refactor PowerShell updates
  src/DotNetBumper.Core/PowerShellScript.cs
Labels: enhancement

#140 Enable style analyzers
  .editorconfig
  Directory.Build.props
  src/DotNetBumper.Core/BumperConfigurationProvider.cs
  src/DotNetBumper.Core/DotNetProcess.cs
  src/DotNetBumper.Core/Logging/BumperLogContext.cs
  src/DotNetBumper.Core/PostProcessors/LeftoverReferencesPostProcessor.cs
  src/DotNetBumper.Core/RuntimeIdentifier.cs
  src/DotNetBumper.Core/Upgraders/PackageVersionUpgrader.cs
  src/DotNetBumper.Core/Upgraders/PowerShellScriptUpgrader.cs
  src/DotNetBumper.MSBuild/BumperBuildLogger.cs
  tests/DotNetBumper.Tests/EndToEndTests.cs
Labels: enhancement, .NET

#141 Solution improvements
  Directory.Build.props
  Directory.Packages.props
  tests/DotNetBumper.Tests/DotNetBumper.Tests.csproj
Labels: enhancement, dependencies, .NET

#145 Bump Microsoft.Extensions.Http.Resilience
  Directory.Packages.props
Labels: dependencies, .NET
