Repository martincostello/dotnet-bumper, pull requests merged in 2024-02, with the labels that each got.

#4 Enable badges
  README.md
Labels: documentation, enhancement

#6 Remove GitHub options
  Directory.Packages.props
  src/DotNetBumper.Core/DotNetBumper.Core.csproj
  src/DotNetBumper.Core/GitHubEnvironment.cs
  src/DotNetBumper.Core/ProjectUpgrader.cs
  src/DotNetBumper.Core/ServiceCollectionExtensions.cs
  src/DotNetBumper.Core/UpgradeOptions.cs
  src/DotNetBumper.Core/UpgradeOptionsValidator.cs
  src/DotNetBumper.Core/UpgradePostConfigureOptions.cs
  src/DotNetBumper/Bumper.cs
  src/DotNetBumper/UpgradePostConfigureOptions.cs
Labels: enhancement

#8 Add option to test after upgrade
  src/DotNetBumper.Core/DotNetProcess.cs
  src/DotNetBumper.Core/DotNetResult.cs
  src/DotNetBumper.Core/ProjectHelpers.cs
  src/DotNetBumper.Core/ProjectUpgrader.cs
  src/DotNetBumper.Core/ServiceCollectionExtensions.cs
  src/DotNetBumper.Core/UpgradeOptions.cs
  src/DotNetBumper.Core/Upgraders/PackageVersionUpgrader.cs
  src/DotNetBumper.Core/Upgraders/Upgrader.cs
  src/DotNetBumper/Bumper.cs
  src/DotNetBumper/UpgradePostConfigureOptions.cs
  tests/DotNetBumper.Tests/EndToEndTests.cs
  tests/DotNetBumper.Tests/Project.cs
  tests/DotNetBumper.Tests/ProjectUpgraderTests.cs
Labels: enhancement

#9 Serverless runtime upgrader
  Directory.Packages.props
  src/DotNetBumper.Core/DotNetBumper.Core.csproj
  src/DotNetBumper.Core/ServiceCollectionExtensions.cs
  src/DotNetBumper.Core/Upgraders/ServerlessUpgrader.cs
  src/DotNetBumper/Properties/launchSettings.json
  tests/DotNetBumper.Tests/Upgraders/ServerlessUpgraderTests.cs
Labels: enhancement

#18 Fix hang during dotnet test
  src/DotNetBumper.Core/DotNetProcess.cs
Labels: bug

#20 Add Windows Terminal spinner
  src/DotNetBumper/Program.cs
Labels: enhancement

#21 Update AWS Lambda Tools defaults
  src/DotNetBumper.Core/ServiceCollectionExtensions.cs
  src/DotNetBumper.Core/Upgraders/AwsLambdaToolsUpgrader.cs
  src/DotNetBumper.Core/Upgraders/ServerlessUpgrader.cs
  src/DotNetBumper.Core/Upgraders/TargetFrameworkUpgrader.cs
  src/DotNetBumper.Core/Upgraders/VisualStudioCodeUpgrader.cs
  src/DotNetBumper.Core/VersionExtensions.cs
  tests/DotNetBumper.Tests/Upgraders/AwsLambdaToolsUpgraderTests.cs
Labels: enhancement

#23 Fix build badge
  README.md
Labels: bug, documentation

#26 Refactor JSON handling
  src/DotNetBumper.Core/JsonExtensions.cs
  src/DotNetBumper.Core/JsonHelpers.cs
  src/DotNetBumper.Core/Upgraders/AwsLambdaToolsUpgrader.cs
  src/DotNetBumper.Core/Upgraders/VisualStudioCodeUpgrader.cs
  src/DotNetBumper.Core/Upgraders/VisualStudioComponentUpgrader.cs
Labels: enhancement

#28 Update any MSBuild properties containing TFMs
  src/DotNetBumper.Core/Upgraders/TargetFrameworkUpgrader.cs
  src/DotNetBumper.Core/Upgraders/VisualStudioCodeUpgrader.cs
  src/DotNetBumper.Core/VersionExtensions.cs
  tests/DotNetBumper.Tests/EndToEndTests.cs
  tests/DotNetBumper.Tests/Upgraders/TargetFrameworkUpgraderTests.cs
Labels: enhancement

#40 Rename Priority to Order
  src/DotNetBumper.Core/ProjectUpgrader.cs
  src/DotNetBumper.Core/Upgraders/GlobalJsonUpgrader.cs
  src/DotNetBumper.Core/Upgraders/IUpgrader.cs
  src/DotNetBumper.Core/Upgraders/PackageVersionUpgrader.cs
  src/DotNetBumper.Core/Upgraders/Upgrader.cs
Labels: enhancement

#44 Add disclaimer
  src/DotNetBumper.Core/IAnsiConsoleExtensions.cs
  src/DotNetBumper.Core/ProjectUpgrader.cs
Labels: enhancement

#43 Support case insensitive docker image declarations
  src/DotNetBumper.Core/Upgraders/DockerfileUpgrader.cs
  tests/DotNetBumper.Tests/Upgraders/DockerfileUpgraderTests.cs
Labels: bug

#48 Preserve file formatting on edit
  Directory.Build.targets
  src/DotNetBumper.Core/DotNetProcess.cs
  src/DotNetBumper.Core/FileHelpers.cs
  src/DotNetBumper.Core/FileMetadata.cs
  src/DotNetBumper.Core/JsonExtensions.cs
  src/DotNetBumper.Core/Upgraders/DockerfileUpgrader.cs
  src/DotNetBumper.Core/Upgraders/GlobalJsonUpgrader.cs
  src/DotNetBumper.Core/Upgraders/ServerlessUpgrader.cs
  src/DotNetBumper.Core/Upgraders/TargetFrameworkUpgrader.cs
  src/DotNetBumper.Core/Upgraders/VisualStudioCodeUpgrader.cs
  tests/DotNetBumper.Tests/JsonExtensionsTests.cs
  tests/DotNetBumper.Tests/Project.cs
  tests/DotNetBumper.Tests/ShouldlyExtensions.cs
  tests/DotNetBumper.Tests/Upgraders/AwsLambdaToolsUpgraderTests.cs
  tests/DotNetBumper.Tests/Upgraders/DockerfileUpgraderTests.cs
  tests/DotNetBumper.Tests/Upgraders/GlobalJsonUpgraderTests.cs
  tests/DotNetBumper.Tests/Upgraders/ServerlessUpgraderTests.cs
  tests/DotNetBumper.Tests/Upgraders/TargetFrameworkUpgraderTests.cs
  tests/DotNetBumper.Tests/Upgraders/VisualStudioCodeUpgraderTests.cs
  tests/DotNetBumper.Tests/Upgraders/VisualStudioComponentUpgraderTests.cs
Labels: bug, enhancement

#50 Add banner
  src/DotNetBumper/Bumper.cs
  tests/DotNetBumper.Tests/EndToEndTests.cs
Labels: bug, enhancement

#51 Fix some TFM updates being missed
  src/DotNetBumper.Core/Upgraders/VisualStudioCodeUpgrader.cs
  tests/DotNetBumper.Tests/DotNetChannelTestData.cs
  tests/DotNetBumper.Tests/FileEncodingTestData.cs
  tests/DotNetBumper.Tests/LambdaRuntimeTestData.cs
  tests/DotNetBumper.Tests/Upgraders/AwsLambdaToolsUpgraderTests.cs
  tests/DotNetBumper.Tests/Upgraders/DockerfileUpgraderTests.cs
  tests/DotNetBumper.Tests/Upgraders/GlobalJsonUpgraderTests.cs
  tests/DotNetBumper.Tests/Upgraders/ServerlessUpgraderTests.cs
  tests/DotNetBumper.Tests/Upgraders/TargetFrameworkUpgraderTests.cs
  tests/DotNetBumper.Tests/Upgraders/VisualStudioCodeUpgraderTests.cs
  tests/DotNetBumper.Tests/Upgraders/VisualStudioComponentUpgraderTests.cs
Labels: bug

#54 Show leftover references
  Directory.Packages.props
  src/DotNetBumper.Core/DotNetBumper.Core.csproj
  src/DotNetBumper.Core/FileHelpers.cs
  src/DotNetBumper.Core/PostProcessors/LeftoverReferencesPostProcessor.cs
  src/DotNetBumper.Core/PostProcessors/PotentialFileEdit.cs
  src/DotNetBumper.Core/PostProcessors/ProjectFile.cs
  src/DotNetBumper.Core/ProjectUpgrader.cs
  src/DotNetBumper.Core/ServiceCollectionExtensions.cs
  src/DotNetBumper.Core/Upgraders/PackageVersionUpgrader.cs
  src/DotNetBumper.Core/VersionExtensions.cs
  tests/DotNetBumper.Tests/BumperTestCase.cs
  tests/DotNetBumper.Tests/DotNetBumper.Tests.csproj
  tests/DotNetBumper.Tests/EndToEndTests.cs
  tests/DotNetBumper.Tests/JsonExtensionsTests.cs
  tests/DotNetBumper.Tests/PostProcessors/LeftoverReferencesPostProcessorTests.cs
  tests/DotNetBumper.Tests/Project.cs
  tests/DotNetBumper.Tests/ShouldlyExtensions.cs
Labels: enhancement

#58 Add custom MSBuild logger
  .github/dependabot.yml
  Directory.Packages.props
  DotNetBumper.sln
  src/DotNetBumper.Core/DotNetBumper.Core.csproj
  src/DotNetBumper.Core/DotNetProcess.cs
  src/DotNetBumper.Core/DotNetResult.cs
  src/DotNetBumper.Core/PostProcessors/DotNetTestPostProcessor.cs
  src/DotNetBumper.Core/PostProcessors/LeftoverReferencesPostProcessor.cs
  src/DotNetBumper.Core/TemporaryFile.cs
  src/DotNetBumper.Core/Upgraders/PackageVersionUpgrader.cs
  src/DotNetBumper.MSBuild/BumperLog.cs
  src/DotNetBumper.MSBuild/BumperLogEntry.cs
  src/DotNetBumper.MSBuild/BumperLogger.cs
  src/DotNetBumper.MSBuild/DotNetBumper.MSBuild.csproj
  tests/DotNetBumper.Tests/BumperLoggerTests.cs
  tests/DotNetBumper.Tests/EndToEndTests.cs
  tests/DotNetBumper.Tests/JsonExtensionsTests.cs
  tests/DotNetBumper.Tests/Project.cs
Labels: enhancement

#61 Preserve JSON and XML new line characters
  src/DotNetBumper.Core/JsonExtensions.cs
  src/DotNetBumper.Core/JsonHelpers.cs
  src/DotNetBumper.Core/Upgraders/TargetFrameworkUpgrader.cs
  tests/DotNetBumper.Tests/Upgraders/AwsLambdaToolsUpgraderTests.cs
  tests/DotNetBumper.Tests/Upgraders/TargetFrameworkUpgraderTests.cs
  tests/DotNetBumper.Tests/Upgraders/VisualStudioCodeUpgraderTests.cs
  tests/DotNetBumper.Tests/Upgraders/VisualStudioComponentUpgraderTests.cs
Labels: enhancement

#62 Add .NET breaking changes link
  src/DotNetBumper.Core/IAnsiConsoleExtensions.cs
  src/DotNetBumper.Core/ProjectUpgrader.cs
Labels: enhancement

#64 Ignore some file types when finding references
  Directory.Packages.props
  src/DotNetBumper.Core/DotNetBumper.Core.csproj
  src/DotNetBumper.Core/PostProcessors/LeftoverReferencesPostProcessor.cs
  tests/DotNetBumper.Tests/PostProcessors/LeftoverReferencesPostProcessorTests.cs
  tests/DotNetBumper.Tests/Project.cs
Labels: enhancement, dependencies, .NET

#67 Emit warnings in JSON log
  src/DotNetBumper.Core/Logging/JsonLogWriter.cs
  src/DotNetBumper.Core/Logging/MarkdownLogWriter.cs
Labels: bug

#69 Bump actionlint to 1.6.27
  .github/workflows/lint.yml
Labels: dependencies, github_actions

#70 Bump actionlint to 1.6.27
  .github/workflows/lint.yml
Labels: dependencies, github_actions

#71 Output changelog
  src/DotNetBumper.Core/Logging/BumperLogContext.cs
  src/DotNetBumper.Core/Logging/JsonLogWriter.cs
  src/DotNetBumper.Core/Logging/MarkdownLogWriter.cs
  src/DotNetBumper.Core/Upgraders/GlobalJsonUpgrader.cs
  src/DotNetBumper.Core/Upgraders/PackageVersionUpgrader.cs
  src/DotNetBumper.Core/Upgraders/ServerlessUpgrader.cs
  src/DotNetBumper.Core/Upgraders/TargetFrameworkUpgrader.cs
  tests/DotNetBumper.Tests/PostProcessors/LeftoverReferencesPostProcessorTests.cs
  tests/DotNetBumper.Tests/ProjectUpgraderTests.cs
  tests/DotNetBumper.Tests/UpgraderFixture.cs
  tests/DotNetBumper.Tests/Upgraders/GlobalJsonUpgraderTests.cs
  tests/DotNetBumper.Tests/Upgraders/ServerlessUpgraderTests.cs
  tests/DotNetBumper.Tests/Upgraders/TargetFrameworkUpgraderTests.cs
Labels: enhancement

#72 Sort references
  src/DotNetBumper.Core/Logging/JsonLogWriter.cs
  src/DotNetBumper.Core/Logging/MarkdownLogWriter.cs
  src/DotNetBumper.Core/PostProcessors/LeftoverReferencesPostProcessor.cs
Labels: enhancement

#77 Update .NET test SDK
  src/DotNetBumper.Core/Upgraders/PackageVersionUpgrader.cs
Labels: enhancement

#78 Consume MimeTypes as source
  Directory.Packages.props
  src/DotNetBumper.Core/DotNetBumper.Core.csproj
  src/DotNetBumper.Core/PostProcessors/MimeTypes.cs
Labels: dependencies, .NET

#79 Set capacity
  src/DotNetBumper.Core/PostProcessors/MimeTypes.cs
Labels: enhancement

#85 Add overall upgrade status to JSON log
  src/DotNetBumper.Core/Logging/BumperLogContext.cs
  src/DotNetBumper.Core/Logging/JsonLogWriter.cs
  src/DotNetBumper.Core/ProjectUpgrader.cs
  tests/DotNetBumper.Tests/Logging/JsonLogWriterTests.cs
Labels: enhancement

#87 Add custom configuration file
  DotNetBumper.sln
  dotnet-bumper-schema.json
  src/DotNetBumper.Core/BumperConfiguration.cs
  src/DotNetBumper.Core/BumperConfigurationLoader.cs
  src/DotNetBumper.Core/BumperConfigurationProvider.cs
  src/DotNetBumper.Core/BumperJsonSerializerContext.cs
  src/DotNetBumper.Core/DotNetBumper.Core.csproj
  src/DotNetBumper.Core/PostProcessors/DotNetTestPostProcessor.cs
  src/DotNetBumper.Core/PostProcessors/LeftoverReferencesPostProcessor.cs
  src/DotNetBumper.Core/ServiceCollectionExtensions.cs
  src/DotNetBumper.Core/UpgradeOptions.cs
  src/DotNetBumper.Core/UpgradeOptionsValidator.cs
  src/DotNetBumper.Core/Upgraders/PackageVersionUpgrader.cs
  src/DotNetBumper/Bumper.cs
  src/DotNetBumper/UpgradePostConfigureOptions.cs
  tests/DotNetBumper.Tests/BumperConfigurationLoaderTests.cs
  tests/DotNetBumper.Tests/BumperConfigurationProviderTests.cs
  tests/DotNetBumper.Tests/EndToEndTests.cs
  tests/DotNetBumper.Tests/PostProcessors/LeftoverReferencesPostProcessorTests.cs
  tests/DotNetBumper.Tests/UpgraderFixture.cs
Labels: enhancement

#92 Update documentation
  README.md
Labels: documentation

#94 Suppress preview-specific warnings
  src/DotNetBumper.Core/BumperConfigurationProvider.cs
  tests/DotNetBumper.Tests/BumperConfigurationProviderTests.cs
Labels: enhancement
